### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by jbucaran** [milankinen/livereactload#139]
@milankinen Hi.

I literally just cloned the repo, cd'd into examples/01-basic-usage, followed the instructions just like so

```
npm i && npm run watch
```

and got this

```
> livereactload-basic-usage-example@2.0.0 watch /Users/x/Code/livereactload/examples/01-basic-usage
> npm run watch:server & npm run watch:bundle & wait


> livereactload-basic-usage-example@2.0.0 watch:server /Users/x/Code/livereactload/examples/01-basic-usage
> nodemon --exec babel-node --ignore bundle.js -- server.js


> livereactload-basic-usage-example@2.0.0 watch:bundle /Users/x/Code/livereactload/examples/01-basic-usage
> watchify site.js -v -t babelify -g envify -p livereactload -o bundle.js

module.js:471
    throw err;
    ^

Error: Cannot find module './lib/browserify-plugin/main.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/x/Code/livereactload/examples/01-basic-usage/node_modules/livereactload/index.js:2:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node server.js`
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/x/.config/verman/node/6.9.1/bin/node" "/Users/x/.config/verman/node/6.9.1/bin/npm" "run" "watch:bundle"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! livereactload-basic-usage-example@2.0.0 watch:bundle: `watchify site.js -v -t babelify -g envify -p livereactload -o bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the livereactload-basic-usage-example@2.0.0 watch:bundle script 'watchify site.js -v -t babelify -g envify -p livereactload -o bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the livereactload-basic-usage-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchify site.js -v -t babelify -g envify -p livereactload -o bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs livereactload-basic-usage-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls livereactload-basic-usage-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/x/Code/livereactload/examples/01-basic-usage/npm-debug.log
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/babel-transform/main.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/x/Code/livereactload/examples/01-basic-usage/node_modules/livereactload/babel-transform.js:2:18)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/x/Code/livereactload/examples/01-basic-usage/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting...
```

The other examples are broken as well, unfortunately.

This must be a problem in my environment, since the last commit to the examples directory was over 5 months ago and I can't be the first to have tried running the examples.

Are there any additional instructions, other than what's written in the examples README, I need to follow?

**Comment by milankinen** [comment]
Shit, I've forgot local package paths to `package.json`. Must fix it, thanks for reporting!

**Comment by milankinen** [comment]
Fix'd 😅
