### ISSUE TITLE
Multiple entries support

### ISSUE THREAD

**Issue by LeiZeng** [milankinen/livereactload#81]
Live server listens on only one port for each entry, if bundle more entries will cause port taken error.
```bash
[14:25:51.055] LiveReactload :: Reload server up and listening in port 4474...
[14:25:51.069] LiveReactload :: Reload server up and listening in port 4474...
[22:25:51] Finished 'dev' after 327 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:4474
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:461:9)
    at process._tickCallback (node.js:367:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by milankinen** [comment]
Hi @LeiZeng! Are you using multiple `watchify`/ `browserify` commands to create your bundles or are you using some kind of plugin/transfrom like `factor-bundle`?

If you are using multiple commands then perhaps you could use `--port` config option?

```javascript
{
  "scripts": {
     "watch:bundle1": "watchify entry1.js -v -t babelify -g envify -p livereactload -o bundle1.js",
     "watch:bundle2": "watchify entry2.js -v -t babelify -g envify -p [ livereactload --port 4475 ] -o bundle2.js",
      ...
  },
  ...
}
```

**Comment by LeiZeng** [comment]
Make sense to have a port configuration, thanks a lot.
I should have set a new port myself.
