### ISSUE TITLE
React app keeps being run in node

### ISSUE THREAD

**Issue by ericwooley** [milankinen/livereactload#86]
I am trying to build a project using livereactload based off of example 1 (but switching to browserify), https://github.com/ericwooley/browserify-react-component and when I include the file that tries to bundle, it runs the entry in node instead of bundling it. Subsequently I get complaints about document not being defined.

```
eferenceError: document is not defined
    at Object.<anonymous> (index.js:7:5)
    at Module._compile (module.js:425:26)
    at loader (/Users/eriwoole/Projects/browserify-react-component/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/eriwoole/Projects/browserify-react-component/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at /Users/eriwoole/Projects/browserify-react-component/node_modules/babel-cli/lib/_babel-node.js:161:27
    at Object.<anonymous> (/Users/eriwoole/Projects/browserify-react-component/node_modules/babel-cli/lib/_babel-node.js:162:7)
    at Module._compile (module.js:425:26)
```

This is how I am packaging it https://github.com/ericwooley/browserify-react-component/blob/master/server.js#L21
```js
// browserify
var b = browserify({
  entries: ['src/index.js'],
  transform: [ [babelify, {}], [envify, {}] ],
  plugin: [watchify, [lrload, {server: false}]]
})
function bundle () {
  b.bundle().pipe(fs.createWriteStream('bundle.js'))
}
b.on('update', bundle)
bundle()

app.get('/', (req, res) => {
  res.sendFile('index', {root: __dirname})
})

app.get('/static/bundle.js', function (req, res) {
  res.sendFile('bundle.js', {root: __dirname})
})

app.listen(3000)
```

Am I missing something? Why is it trying to render at bundle time?

**Comment by milankinen** [comment]
Aah yeah so you are using watchify directly from your node app? Interesting.. never thought that as a use case! 

I don't understand why this is happening, there should be absolutely no evaluation in LiveReactload's browserify plugin side. Does this happen if you remove `lrload` plugin? Could it be possible to get a link to a repository/project having this issue?

**Comment by milankinen** [comment]
Marking this as question until I get more info.

**Comment by milankinen** [comment]
Updated in version `2.2.0`
